version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    deploy:
      replicas: 1  

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:mongodb@mongodb:27017/mern-stack-db?authSource=admin
    depends_on:
      - mongodb
    deploy:
      replicas: 2  

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server
    deploy:
      replicas: 2 

volumes:
  mongo_data:
